### PR TITLE
feat: add @AutoConfigureJdbc to @MybatisPlusTest to enable auto local…

### PR DESCRIPTION
**Pull request by fishautumn**
… schema.sql for in-memory database

### 该Pull Request关联的Issue

https://github.com/baomidou/mybatis-plus/issues/4624

### 修改描述

在 @MybatisPlusTest 中引入 @AutoConfigureJdbc

### 测试用例

com.baomidou.mybatisplus.test.autoconfigure.MybatisPlusSampleTest#testInsert

### 修复效果的截屏
image

### CODE REVIEW

**Comment by miemieYaho** [comment]
https://github.com/mybatis/spring-boot-starter/blob/master/mybatis-spring-boot-test-autoconfigure/src/main/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTest.java

**Comment by fishautumn** [comment]
> https://github.com/mybatis/spring-boot-starter/blob/master/mybatis-spring-boot-test-autoconfigure/src/main/java/org/mybatis/spring/boot/test/autoconfigure/MybatisTest.java

是问题已经修正了吗, 还是建议把 issue 提到 mybatis 项目?

**Comment by miemieYaho** [comment]
你去问问mybatis这算问题不吧

**Comment by fishautumn** [comment]
> 你去问问mybatis这算问题不吧

@miemieYaho  MyBatis 项目貌似是通过其他方式已经支持了.

这个是我和他们的讨论: https://github.com/mybatis/spring-boot-starter/issues/681

**Pull request closed without merging**
