### PR TITLE
Add support to Gauss database

### PR DESCRIPTION
**Pull request by Shoothzj**
### 修改描述
Add support for gaussDB 200
- GaussDB200 https://support.huaweicloud.com/intl/en-us/mgtg-dws/dws_01_0077.html

### CODE REVIEW

**Comment by Shoothzj** [comment]
@miemieYaho Could you please take a look again, thanks

**Comment by miemieYaho** [comment]
image
so?

**Comment by Shoothzj** [comment]
> image so?

Excuse me, is that you mean we can support gauss200, I don't find it in `JDBCUtils`. neither `gauss200` nor `gaussdb`

**Comment by miemieYaho** [comment]
where is the gauss200 and zenith document?

**Pull request closed without merging**
